### PR TITLE
Ledaerboard update

### PR DESCRIPTION
**Pull request by LikerK**
While working on the project, I added two buttons to the "top 10 contributors" leaderboard: for the past week and for the past month

### CODE REVIEW

**Comment by acidmaksim** [comment]
@LikerK у тебя конфликт здесь

**Comment by zhabinka** [comment]
@ashikov запусти, плиз, тесты

**Comment by acidmaksim** [comment]
@zhabinka мержу?

**Comment by dzencot** [comment]
@zhabinka мержим?

**Pull request merged**
